name: cruzhacks-2021-website

on:
  push:
    branches: [ main, production ]
  pull_request:
    branches: [ main, production ]

jobs:
  static-analysis: 
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.11.0
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint
  
  js-tests:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2 
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.11.0
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Running JS tests 
        run: yarn test:ci

  build:
    runs-on: ubuntu-latest
    needs: [js-tests, static-analysis]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.11.0
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Create Production Build
        run: yarn build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build

  auto-deploy-to-prod:
    runs-on: ubuntu-latest
    needs: [build, js-tests, static-analysis]
    if: github.ref == 'refs/heads/production'
    steps:
      - uses: actions/checkout@v2
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:cruzhacks-2021-website
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

  auto-deploy-to-test:
    runs-on: ubuntu-latest
    needs: [build, js-tests, static-analysis]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:cruzhacks-2021-website-test
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
