name: cruzhacks-2021-website

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  static-analysis: 
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v2 
      - name: Run Linter 
        run: echo Linter will be run here
  
  js-tests:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2 
      - name: Running JS tests 
        run: echo JS testing will be here

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Creating production build
        run: echo creating a production build
