name: cruzhacks-2021-website

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  static-analysis: 
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v2
      - name: Run Linter 
        run: yarn lint
  
  js-tests:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2 
      - name: Running JS tests 
        run: echo JS testing will be here

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Creating production build
        run: echo creating a production build

  auto-deploy-to-prod:
    runs-on: ubuntu-latest
    needs: [build, js-tests, static-analysis]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Auto Deploy to Production
        run: echo This would ideally autodeploy to firebase
